# Generated by Django 5.2.10 on 2026-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='individual_attendance_mode',
            field=models.CharField(blank=True, choices=[('FACE_ONLY', 'Face Only'), ('FACE_LOCATION', 'Face + Location')], default=None, max_length=20, null=True),
        ),
    ]
