# Generated by Django 5.2.10 on 2026-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_individual_attendance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual_attendance_mode',
            field=models.CharField(blank=True, choices=[('FACE_ONLY', 'Face Only'), ('FACE_LOCATION', 'Face + Location')], max_length=20, null=True),
        ),
    ]
