from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from performance.models import PerformanceResult
from account.models import User
from reports.utils.pdf_base import create_pdf_response
from .utils.performance_tables import performance_list_table
from attendance.services import get_organisation
from performance.services.performence_quer_set import get_performance_queryset
from datetime import date


from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle



# Create your views here.

class PerformanceListPDFAPIView(APIView):

    def get(self, request):
        user = request.user
        organisation = get_organisation(user)

        if user.user_type not in ["ORG_ADMIN", "HR"]:
            return Response({"error": "No permission"}, status=status.HTTP_403_FORBIDDEN)

        queryset = get_performance_queryset(request, user)
        if not queryset.exists():
            return Response({"error": "No data"}, status=status.HTTP_400_BAD_REQUEST)

        report = create_pdf_response("performance_report.pdf")
        doc = SimpleDocTemplate(
            report, 
            pagesize=A4,
            rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
        )

        
        styles = getSampleStyleSheet()
        
        # Header Style (Company Name)
        styles.add(ParagraphStyle(
            name='OrgHeader',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#1D3557"), 
            alignment=TA_CENTER,
            spaceAfter=5,
            fontName='Helvetica-Bold'
        ))

        styles.add(ParagraphStyle(
            name='ReportTitle',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#457B9D"), # Muted Blue
            alignment=TA_CENTER,
            spaceAfter=20,
            fontName='Helvetica'
        ))

        styles.add(ParagraphStyle(
            name='MetaStyle',
            fontSize=9,
            leading=12,
            textColor=colors.grey,
            alignment=TA_LEFT
        ))

        elements = []

        
        elements.append(Paragraph(organisation.name.upper(), styles["OrgHeader"]))
        elements.append(Paragraph("Employee Performance Report", styles["ReportTitle"]))
        
        meta_data = [
            [f"Generated By: {user.name}", f"Date: {date.today().strftime('%B %d, %Y')}"],
            [f"Role: {user.user_type.replace('_', ' ')}", f"Organisation: {organisation.name}"]
        ]
        meta_table = Table(meta_data, colWidths=[250, 250])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.grey),
            ('ALIGN', (0,0), (0,-1), 'LEFT'),
            ('ALIGN', (1,0), (1,-1), 'RIGHT'),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 20))

        
        description = (
            f"This report serves as a formal evaluation of personnel performance within <b>{organisation.name}</b>. "
            "It aggregates data regarding attendance, task delivery, and managerial assessments to provide "
            "a comprehensive oversight of operational efficiency. This is a <b>Confidential</b> document."
        )
        elements.append(Paragraph(description, styles["Normal"]))
        elements.append(Spacer(1, 25))

        
        table = performance_list_table(queryset)
        
       
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1D3557")), 
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9FA")]), 
        ]))
        
        elements.append(table)

        
        doc.build(elements)
        return report