# Generated by Django 6.0.1 on 2026-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='employid_proofs/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='emplaoy_photos/'),
        ),
    ]
