# Generated by Django 6.0.1 on 2026-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_encode',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
