# Generated by Django 6.0.1 on 2026-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registration_doc', models.FileField(blank=True, null=True, upload_to='org_documents/')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('creates_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
