# Generated by Django 5.2.10 on 2026-02-01 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_oganisation_latitude_oganisation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oganisation',
            name='attendance_mode',
            field=models.CharField(choices=[('FACE_ONLY', 'Face Only'), ('FACE_LOCATION', 'Face + Location')], default='FACE_LOCATION', max_length=20),
        ),
        migrations.AddField(
            model_name='oganisation',
            name='full_day_last_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='oganisation',
            name='half_day_cutoff_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
