# Generated by Django 5.2.10 on 2026-02-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_oganisation_attendance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oganisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
