# Generated by Django 5.2.10 on 2026-02-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_oganisation_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=150)),
                ('org_email', models.EmailField(max_length=254)),
                ('org_phone', models.CharField(blank=True, max_length=15)),
                ('org_address', models.TextField(blank=True)),
                ('registration_doc', models.FileField(blank=True, null=True, upload_to='org_docs/')),
                ('registration_number', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('attendance_mode', models.CharField(choices=[('FACE_ONLY', 'Face Only'), ('FACE_LOCATION', 'Face + Location')], max_length=20)),
                ('full_day_last_time', models.TimeField(blank=True, null=True)),
                ('half_day_cutoff_time', models.TimeField(blank=True, null=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=15)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_photo', models.ImageField(blank=True, null=True, upload_to='org_admin/photo/')),
                ('admin_id_proof', models.FileField(blank=True, null=True, upload_to='org_admin/idproof/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
