# Generated by Django 6.0.1 on 2026-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hr_face_encode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='desigination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
