# Generated by Django 5.2.10 on 2026-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employeerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
