# Generated by Django 5.2.10 on 2026-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employeerequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
