# Generated by Django 5.2.10 on 2026-02-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employeerequest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='employee_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
