# Generated by Django 5.2.10 on 2026-02-04 14:06

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('organizations', '0003_oganisation_attendance_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chatgroupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('organization', 'user1', 'user2')},
        ),
    ]
