# Generated by Django 6.0.1 on 2026-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='desigination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
