# Generated by Django 6.0.1 on 2026-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0002_teamlead_desigination'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='face_encode',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
