# Generated by Django 5.2.10 on 2026-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamlead', '0003_teamlead_face_encode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
