# Generated by Django 6.0.1 on 2026-01-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_employee_face_encode_alter_employee_department'),
        ('teamlead', '0003_teamlead_face_encode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_lead_file', models.FileField(blank=True, null=True, upload_to='task_files/team_lead/')),
                ('employee_file', models.FileField(blank=True, null=True, upload_to='task_files/employee/')),
                ('employee_replay_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ASSIGNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('last_submission_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamlead.teamlead')),
            ],
        ),
    ]
