# Generated by Django 6.0.1 on 2026-01-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('SUBMITTED', 'Submitted'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ASSIGNED', max_length=20),
        ),
    ]
