# Generated by Django 5.2.10 on 2026-02-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_oganisation_attendance_mode_and_more'),
        ('tasks', '0003_alter_taskassignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.oganisation'),
        ),
    ]
