# Generated by Django 5.2.10 on 2026-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskassignment_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='team_lead_replay_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
