# Generated by Django 6.0.1 on 2026-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountent',
            name='face_encode',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
