# Generated by Django 5.2.10 on 2026-02-06 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_oganisation_attendance_mode_and_more'),
        ('teamlead', '0004_alter_teamlead_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=150)),
                ('file_type', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('encrypted_file', models.FileField(upload_to='secure_files/')),
                ('owner_role', models.CharField(max_length=30)),
                ('allow_view', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_share', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.oganisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamlead.teamlead')),
            ],
        ),
    ]
