# Generated by Django 5.2.10 on 2026-02-06 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0001_initial'),
        ('teamlead', '0004_alter_teamlead_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_role', models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('TEAM_LEAD', 'Team Lead'), ('EMPLOYEE', 'Employee'), ('HR', 'HR'), ('ACCOUNTANT', 'Accountant')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secure_files.securefile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_teamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamlead.teamlead')),
            ],
        ),
    ]
