# Generated by Django 5.2.10 on 2026-02-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0002_fileshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileshare',
            name='shared_teamlead',
        ),
    ]
