# Generated by Django 5.2.10 on 2026-02-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0003_remove_fileshare_shared_teamlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileshare',
            name='shared_role',
        ),
        migrations.AddField(
            model_name='fileshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_shared_by_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
