# Generated by Django 5.2.10 on 2026-02-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0004_remove_fileshare_shared_role_fileshare_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='message',
            field=models.CharField(blank=True, null=True),
        ),
    ]
