# Generated by Django 5.2.10 on 2026-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0005_fileshare_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='encrypted_file_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
