# Generated by Django 5.2.10 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_files', '0006_securefile_encrypted_file_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='can_download',
            field=models.BooleanField(default=True),
        ),
    ]
